---
apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  annotations:
    build.knative.dev/docker-0: https://registry.cn-hangzhou.aliyuncs.com
type: kubernetes.io/basic-auth
data:
  # Use 'echo -n "username" | base64' to generate this string
  username: 'xxx='
  # Use 'echo -n "password" | base64' to generate this string
  password: 'yyyjjj=='

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-bot
secrets:
  - name: basic-user-pass

---
apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: build-helloworld-simple-app
spec:
  serviceAccountName: build-bot
  source:
    git:
      url: https://github.com/knative-sample/helloworld-go.git
      revision: master
  steps:
  - name: build-and-push
    image: "registry.cn-hangzhou.aliyuncs.com/knative-release/kaniko-project-executor:v0.6.0"
    args:
    - "--dockerfile=/workspace/Dockerfile"
    # Replace meteatamel with your actual DockerHub
    - "--destination=registry.cn-hangzhou.aliyuncs.com/knative-sample/helloworld-go:01"
    env:
    - name: DOCKER_CONFIG
      value: /builder/home/.docker

