---
apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: helloworld-go
spec:
  serviceAccountName: build-bot
  source:
    git:
      url: https://github.com/knative-sample/helloworld-go.git
      revision: master
  steps:
  - name: build-and-push
    image: "registry.cn-hangzhou.aliyuncs.com/knative-release/kaniko-project-executor:v0.6.0"
    args:
    - "--dockerfile=/workspace/Dockerfile"
    # Replace meteatamel with your actual DockerHub
    - "--destination=registry.cn-hangzhou.aliyuncs.com/knative-sample/helloworld-go:218a0ae4"
    env:
    - name: DOCKER_CONFIG
      value: /builder/home/.docker
