apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: helloworld-go
      annotations:
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/knative-sample/helloworld-go:218a0ae4
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: TARGET
              value: "https://github.com/knative-sample/helloworld-go"
