apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: knative-build-role-binding
  namespace: default
  labels:
    app: knative-build
    knative: knative-build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: knative-build
subjects:
  - kind: ServiceAccount
    name: knative-build
    namespace: default
