---
apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: build-helloworld-simple-app
spec:
  serviceAccountName: build-bot
  source:
    git:
      url: https://github.com/knative-sample/helloworld-go.git
      revision: master
  template:
    name: helloworld-go-build
    arguments:
    - name: IMAGE
      value: registry.cn-hangzhou.aliyuncs.com/knative-sample/helloworld-go:{{.ShortCommitid}}

